version: 2
updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /worker
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /app
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /worker
    schedule:
      interval: monthly
