/**
 * UI strings for the public manual. The manual language is chosen per brand
 * (brand_settings.defaultLanguage), independently of the admin locale, so the
 * public shell and blocks read from this small dictionary via context.
 * To add a manual language, add its dictionary to STRINGS (TypeScript checks
 * that it has every key) and the language to project.inlang/settings.json.
 */
import { getContext, setContext } from 'svelte';

const STRINGS = {
	en: {
		search: 'Search',
		searchPlaceholder: 'Search the manual…',
		searchEmpty: 'No results for',
		searchHintNavigate: 'to navigate',
		searchHintOpen: 'to open',
		searchHintClose: 'to close',
		close: 'Close',
		menu: 'Menu',
		skipToContent: 'Skip to content',
		themeLight: 'Switch to light theme',
		themeDark: 'Switch to dark theme',
		edit: 'Edit',
		onThisPage: 'On this page',
		home: 'Home',
		notFoundTitle: 'Page not found',
		notFoundBody: 'This page does not exist or has been moved. Try the search, or start again from the beginning.',
		errorTitle: 'Something went wrong',
		errorBody: 'The page could not be loaded. Please try again in a moment.',
		backHome: 'Back to the manual',
		inThisSection: 'In this section',
		copy: 'Copy',
		copied: 'Copied',
		copyHex: 'Copy HEX',
		copyLink: 'Copy link to section',
		colors: 'Colors',
		colorCount: (n: number) => `${n} ${n === 1 ? 'color' : 'colors'}`,
		onWhite: 'on white',
		onBlack: 'on black',
		production: 'Production',
		noColors: 'No colors have been added yet.',
		noFonts: 'No fonts have been added yet.',
		noStyles: 'No text styles are defined yet.',
		noRules: 'No rules are defined yet.',
		addRules: 'Add languages and typographic rules in the editor.',
		noImages: 'There are no images in the selected folder.',
		noIcons: 'There are no icons in the selected folder.',
		noAssets: 'No assets match the selected folder and tags.',
		noFiles: 'No files match the selected folder and tags.',
		style: 'Style', size: 'Size', lineHeight: 'Line height', weight: 'Weight', tracking: 'Tracking',
		category: 'Category', rule: 'Rule', correct: 'Correct', wrong: 'Wrong',
		clearspace: 'Clear space', minSize: 'Minimum size', xHeight: '× x-height',
		columns: 'Columns', rows: 'Rows', gutter: 'Gutter', gutterRows: 'Gutter (rows)', margins: 'Margins',
		maxWidth: 'Max width', format: 'Format', medium: 'Medium', print: 'Print',
		do: 'Do', dont: "Don't",
		compare: 'Compare before and after',
		before: 'Before', after: 'After',
		previous: 'Previous', next: 'Next',
		openImage: 'Open image',
		imageOf: (i: number, n: number) => `${i} of ${n}`,
		download: 'Download',
		downloadAll: 'Download all',
		htmlPreview: 'Isolated HTML preview',
		videoFallback: 'Open video',
		embedUnsupported: 'This link cannot be embedded.',
		openLink: 'Open',
		subpages: 'Pages in this section',
		colorFormat: 'Colour format',
		textColor: 'Text colour',
		backgroundColor: 'Background colour',
		swapColors: 'Swap',
		contrastRatio: 'Contrast ratio',
		smallText: 'Normal text',
		largeText: 'Large text (18pt+ or 14pt bold)',
		uiComponents: 'UI components & graphics',
		fail: 'Fail',
		clearZone: 'Clear space',
		logoMinHeight: 'Minimum logo height',
		onScreens: 'on screens',
		inPrint: 'in print',
		logoVariant: 'Logo version',
		paddingHorizontal: 'Horizontal padding',
		paddingVertical: 'Vertical padding',
		pngWidth: 'PNG width in pixels',
		downloadAllVersions: 'Download all versions (ZIP)',
		logoPackHint: 'Originals, SVG and PNG in 512, 1024 and 2048 px with the padding above',
		pangram: 'The quick brown fox jumps over the lazy dog',
		fontRoles: { display: 'Display', body: 'Text', mono: 'Monospace', accent: 'Accent' },
		downloadFont: 'Download typeface',
		fontSource: 'Typeface source',
		fontWeights: 'Weights in use',
		fontInfo: 'Typeface information',
		fontFamily: 'Family',
		foundry: 'Foundry',
		license: 'Licence',
		fontType: 'Type',
		variableFont: 'Variable font',
		staticFont: 'Static font',
		axes: 'Axes',
		formats: 'Formats',
		glyphs: 'Characters',
		fontTester: 'Type tester',
		italic: 'Italic',
		usage: 'Use',
		forAi: 'For AI tools',
		aiExport: 'AI export (Markdown)',
		aiExportHint: 'The whole manual in one file for ChatGPT, Claude and others',
		mcpConnect: 'Connect an AI agent (MCP)',
		mcpHint: 'Copy the server URL into Claude, Cursor or VS Code',
		urlCopied: 'URL copied',
	},
	cs: {
		search: 'Hledat',
		searchPlaceholder: 'Hledat v manuálu…',
		searchEmpty: 'Žádné výsledky pro',
		searchHintNavigate: 'pohyb',
		searchHintOpen: 'otevřít',
		searchHintClose: 'zavřít',
		close: 'Zavřít',
		menu: 'Menu',
		skipToContent: 'Přeskočit na obsah',
		themeLight: 'Přepnout na světlý motiv',
		themeDark: 'Přepnout na tmavý motiv',
		edit: 'Upravit',
		onThisPage: 'Na této stránce',
		home: 'Úvod',
		notFoundTitle: 'Stránka nenalezena',
		notFoundBody: 'Tato stránka neexistuje nebo byla přesunuta. Zkuste vyhledávání, nebo začněte znovu od úvodu.',
		errorTitle: 'Něco se pokazilo',
		errorBody: 'Stránku se nepodařilo načíst. Zkuste to prosím za chvíli znovu.',
		backHome: 'Zpět do manuálu',
		inThisSection: 'V této sekci',
		copy: 'Kopírovat',
		copied: 'Zkopírováno',
		copyHex: 'Kopírovat HEX',
		copyLink: 'Kopírovat odkaz na sekci',
		colors: 'Barvy',
		colorCount: (n: number) => `${n} ${n === 1 ? 'barva' : n < 5 ? 'barvy' : 'barev'}`,
		onWhite: 'na bílé',
		onBlack: 'na černé',
		production: 'Výroba',
		noColors: 'Žádné barvy zatím nebyly přidány.',
		noFonts: 'Žádné fonty zatím nebyly přidány.',
		noStyles: 'Žádné typografické styly zatím nejsou definovány.',
		noRules: 'Žádná pravidla zatím nejsou definována.',
		addRules: 'Přidejte jazyky a typografická pravidla v editoru.',
		noImages: 'Ve vybrané složce nejsou žádné obrázky.',
		noIcons: 'Ve vybrané složce nejsou žádné ikony.',
		noAssets: 'Výběru složky a tagů neodpovídají žádné assety.',
		noFiles: 'Výběru složky a tagů neodpovídají žádné soubory.',
		style: 'Styl', size: 'Velikost', lineHeight: 'Řádkování', weight: 'Váha', tracking: 'Prostrkání',
		category: 'Kategorie', rule: 'Pravidlo', correct: 'Správně', wrong: 'Špatně',
		clearspace: 'Ochranná zóna', minSize: 'Min. velikost', xHeight: '× výška X',
		columns: 'Sloupce', rows: 'Řádky', gutter: 'Mezera', gutterRows: 'Mezera (řádky)', margins: 'Okraje',
		maxWidth: 'Max. šířka', format: 'Formát', medium: 'Médium', print: 'Tisk',
		do: 'Ano', dont: 'Ne',
		compare: 'Porovnat před a po',
		before: 'Před', after: 'Po',
		previous: 'Předchozí', next: 'Další',
		openImage: 'Otevřít obrázek',
		imageOf: (i: number, n: number) => `${i} z ${n}`,
		download: 'Stáhnout',
		downloadAll: 'Stáhnout vše',
		htmlPreview: 'Izolovaný náhled HTML',
		videoFallback: 'Otevřít video',
		embedUnsupported: 'Tento odkaz nelze vložit.',
		openLink: 'Otevřít',
		subpages: 'Stránky v této sekci',
		colorFormat: 'Formát barvy',
		textColor: 'Barva textu',
		backgroundColor: 'Barva pozadí',
		swapColors: 'Prohodit',
		contrastRatio: 'Výsledný kontrast',
		smallText: 'Běžný text',
		largeText: 'Velký text (18pt+ nebo 14pt tučně)',
		uiComponents: 'UI komponenty a grafika',
		fail: 'Nevyhovuje',
		clearZone: 'Ochranná zóna',
		logoMinHeight: 'Minimální výška loga',
		onScreens: 'na obrazovkách',
		inPrint: 'v tisku',
		logoVariant: 'Verze loga',
		paddingHorizontal: 'Horizontální okraje',
		paddingVertical: 'Vertikální okraje',
		pngWidth: 'Šířka PNG v pixelech',
		downloadAllVersions: 'Stáhnout všechny verze (ZIP)',
		logoPackHint: 'Originály, SVG a PNG v 512, 1024 a 2048 px s nastavenými okraji',
		pangram: 'Příliš žluťoučký kůň úpěl ďábelské ódy',
		fontRoles: { display: 'Nadpisové', body: 'Textové', mono: 'Neproporcionální', accent: 'Doplňkové' },
		downloadFont: 'Stáhnout písmo',
		fontSource: 'Zdroj písma',
		fontWeights: 'Používané řezy písma',
		fontInfo: 'Informace o písmu',
		fontFamily: 'Rodina',
		foundry: 'Písmolijna',
		license: 'Licence',
		fontType: 'Typ',
		variableFont: 'Variabilní písmo',
		staticFont: 'Statické písmo',
		axes: 'Osy',
		formats: 'Formáty',
		glyphs: 'Znaky',
		fontTester: 'Tester písma',
		italic: 'Kurzíva',
		usage: 'Použití',
		forAi: 'Pro AI nástroje',
		aiExport: 'AI export (Markdown)',
		aiExportHint: 'Celý manuál v jednom souboru pro ChatGPT, Claude a další',
		mcpConnect: 'Připojit AI agenta (MCP)',
		mcpHint: 'Zkopírujte adresu serveru do Claude, Cursoru nebo VS Code',
		urlCopied: 'Adresa zkopírována',
	},
};

export type ManualLanguage = keyof typeof STRINGS;
export type ManualStrings = (typeof STRINGS)['en'];
// Every language must define every string the English dictionary has
const _complete: Record<ManualLanguage, ManualStrings> = STRINGS;
void _complete;

export const MANUAL_LANGUAGES = Object.keys(STRINGS) as ManualLanguage[];

/** A brand's language setting → a language the manual has strings for (English otherwise). */
export function toManualLanguage(value: unknown): ManualLanguage {
	return MANUAL_LANGUAGES.includes(value as ManualLanguage) ? (value as ManualLanguage) : 'en';
}

const KEY = Symbol('manual-ui-strings');

export function manualStrings(lang: ManualLanguage): ManualStrings {
	return STRINGS[lang] ?? STRINGS.en;
}

/** Provide a getter so consumers stay reactive when the language changes. */
export function setManualStrings(get: () => ManualStrings) {
	setContext(KEY, get);
}

export function useManualStrings(): () => ManualStrings {
	return getContext<(() => ManualStrings) | undefined>(KEY) ?? (() => STRINGS.en);
}
