// Regenerates src/lib/icons from scripts/icon-map.json.
// Each export keeps the component name used across the app and points it at a
// Material Symbols glyph (Outlined, weight 300). Run: node scripts/generate-icons.mjs
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';

const map = JSON.parse(readFileSync('scripts/icon-map.json', 'utf8'));
const pkg = '@material-symbols/svg-300/outlined';
const outDir = 'src/lib/icons/glyphs';

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const exports = [];
for (const [name, glyph] of Object.entries(map).sort(([a], [b]) => a.localeCompare(b))) {
	if (!existsSync(`node_modules/${pkg}/${glyph}.svg`)) throw new Error(`Missing glyph ${glyph} for ${name}`);
	writeFileSync(`${outDir}/${name}.svelte`, `<script lang="ts">
	import MaterialIcon from '../MaterialIcon.svelte';
	import svg from '${pkg}/${glyph}.svg?raw';
	let props = $props();
</script>

<MaterialIcon {svg} {...props} />
`);
	exports.push(`export { default as ${name} } from './glyphs/${name}.svelte';`);
}

writeFileSync('src/lib/icons/index.ts', `// Generated by scripts/generate-icons.mjs — edit scripts/icon-map.json instead.
// Icon set: Google Material Symbols, Outlined, weight 300.
import type { Component } from 'svelte';

/** Any icon exported from this module. */
export type IconComponent = Component<{ size?: number | string; stroke?: number | string; class?: string; [attr: string]: unknown }>;

${exports.join('\n')}
`);
console.log(`Generated ${exports.length} icons`);
